### ISSUE TITLE
MSVC Build Errors.

### ISSUE THREAD

**Issue by DontBelieveMe** [Gigabyte-Giant/Burst#13]
When I tried to build with MSVC it gave compile errors - They are really just MSVC complaining about nothing:
- `strdup` is not standard ANSI C, but rather POSIX. (This could be mitigated by either providing a custom function or something like
  
  ``` c
  #ifdef _MSC_VER
    #define strdup _strdup  // _strdup is what Microsoft is saying is conformant to ISO C & C++.
  #endif
  ```
-  And that `fopen` is unsafe. This is just microsoft being ridiculous. It can be solved by:
  
  ``` c
  #ifdef _MSC_VER
    #define _CRT_SECURE_NO_WARNINGS
  #endif
  ```

These are pretty simple fixes, but the only issue is you don't appear to have a `Common.h` or `Utils.h` file (These errors happen in multiple different files), and I don't want to go creating files for small things like this.  These defines also need to be defined before any other #include.

**Comment by bytorbrynden** [comment]
Thanks for reporting, I'll fix these issues shortly.

Also, thanks for the extra information, I really appreciate it.

**Comment by bytorbrynden** [comment]
@DontBelieveMe: https://github.com/BurstLanguage/Burst/commit/eb5fc26f89ca63f2285c3df442182ef2fb8626e2 should fix _most_ of the compiler warnings that you mentioned.
I did a build on my Windows 10 VM, and I was able to verify that **all of the warnings related to the use of `strdup`, are gone**.

That being said, there is still a warning about the use of `fopen`, [despite the definition of `_CRT_SECURE_NO_WARNINGS`](https://github.com/BurstLanguage/Burst/commit/eb5fc26f89ca63f2285c3df442182ef2fb8626e2#diff-4c022762612659a56746230d8957522aR11).

I'll investigate further.

**Edit**: I think I'm just going to go ahead and create a wrapper around `fopen_s` to "replicate" the `fopen` function, but only for MSVC.

**Comment by bytorbrynden** [comment]
Closing this as-of https://github.com/BurstLanguage/Burst/commit/eb5fc26f89ca63f2285c3df442182ef2fb8626e2 and https://github.com/BurstLanguage/Burst/commit/fc7644d998670707da2d4c285aa157244a6f309c.

**Comment by DontBelieveMe** [comment]
The `fopen` wrapper is okay - the `_CRT_SECURE_NO_WARNINGS` needs to be defined before _all_ other includes, including standard library ones. Otherwise the header containing `fopen` will not know at compile time that it should not complain about it. I just thought I'd mention.

**Comment by bytorbrynden** [comment]
> The fopen wrapper is okay - the _CRT_SECURE_NO_WARNINGS needs to be defined before all other includes, including standard library ones. Otherwise the header containing fopen will not know at compile time that it should not complain about it. I just thought I'd mention.

That makes sense. I'll stick with my `fopen` wrapper for now, though.
