### ISSUE TITLE
Why not just use normal looking ints?

### ISSUE THREAD

**Issue by DontBelieveMe** [Gigabyte-Giant/Burst#14]
Why does the project often use the hexadecimal equivalents of plain integers? It just seems to make things more unreadable. 
For example for integer constants:

``` c
  #define BURST_MIN_ARG_COUNT 0x2 // Just 2
  #define BURST_MAX_ARG_COUNT 0xA // Just 10. I shouldn't have to think about how many arguments are max, however simple it may be. I think it should be simple to read.
```

It just seems a little unnecessary to use potentially confusing hexadecimal representations, meaning it is not always _immediately_ evident what the code does. 
Another example:

``` c
  for (int inputTokenIndex = 0x0; ... ) // Why not just use 0
  {
     pOutputTokenValue = (char *) realloc(pOutputTokenValue, (
                sizeof(char) * (outputTokenValueLength + 0x1); // Or 1
  }
```

Note: there may be a really good reason for doing this, its just I can't think of it. Also It makes sense for `#define`ing (bit) flags. Just not simple integer values.
I also don't think there is any difference at a compiler level either.

**Comment by bytorbrynden** [comment]
While yes, using hexadecimal everywhere is probably unnecessary, I'm doing it because of this little guy:

![my dog](http://gigabytegiant.me/images/hex1.jpg)

...I named him "Hex" when I adopted him, so that's why I'm doing it.

**Comment by DontBelieveMe** [comment]
Fair enough. I would probably do the same, its just there are not many data types called Fred, sadly.
