### ISSUE TITLE
Create logo for project

### ISSUE THREAD

**Issue by bytorbrynden** [Gigabyte-Giant/Burst#3]
This should be simple enough, but I'm nothing in the art department.

**Comment by SharkFinPro** [comment]
What do you want it to look like?

Do you want it as a PNG? i could give it a try..

**Comment by bytorbrynden** [comment]
Unfortunately, I don't have any ideas about what I want it to look like @SharkFinPro.

And yes, PNG [with transparency] would be fine.

**Comment by SharkFinPro** [comment]
ok

**Comment by kingcodefish** [comment]
I think I have a pretty good idea for a logo for Burst. Let me see if I can work something up. I may do it in Illustrator and then just convert to raster, I think it'd be easier that way.

**Comment by kingcodefish** [comment]
How's this?
![burst](https://cloud.githubusercontent.com/assets/8534813/16826317/6c41d628-494a-11e6-9989-6011e0cc0ec1.png)

**Comment by bytorbrynden** [comment]
@kingcodefish, that's a start for sure. The blue doesn't really seem to fit, though.

Also, is the word "Burst" really necessary in a logo?
