### ISSUE TITLE
Document the goal(s) of the project

### ISSUE THREAD

**Issue by bytorbrynden** [Gigabyte-Giant/Burst#6]
From what I've seen, people tend to show more interest in a project when they know what its goals are.

I think it might be a good idea to document, in a public place, this project's goals.

**Comment by Gigabyte-Giant** [comment]
A copy of the document that will be used to describe each of the goals for this project, can be found [here](https://docs.google.com/document/d/11nFGH-FsfpQKYslQUIrXKfse0zZlbtvjPvxZ7PboUBg/edit?usp=sharing).

**Comment by bytorbrynden** [comment]
Started, and thus completed, in https://github.com/BurstLanguage/Burst/commit/76361ce276b88aaf0c2b7544fad9051a290ca463.
