### ISSUE TITLE
Implement AST and AST Nodes

### ISSUE THREAD

**Issue by bytorbrynden** [Gigabyte-Giant/Burst#8]
This was started in https://github.com/BurstLanguage/Burst/commit/391f0047666f7cea09893cf6828cf0deae296004.

**Comment by SharkFinPro** [comment]
why are you making this an issue :/

**Comment by bytorbrynden** [comment]
@SharkFinPro, it's a task, not an issue. I use GitHub's issue tracker to track tasks **and** issues.

**Comment by SharkFinPro** [comment]
ok

**Comment by bytorbrynden** [comment]
A fairly nice AST has been implemented, and can be found [here](https://github.com/BurstLanguage/Burst/tree/master/Include/Parser/AST).
